name: Big_Red_Timer
description: A pomodoro timer built using the dart programming language.
# version: 1.0.0
#homepage: https://www.example.com
author: Emmet Delaney <emmetdel@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
